title: Analytics In Technical Writing
description: A guide to the use of readability and web analytics tools in technical writing.
theme: just-the-docs

footer_content: "Copyright &copy; 2025 Piotr Kalarus.

url: https://just-the-docs.github.io