title: Analytics In Technical Writing
description: A guide to the use of readability and web analytics tools in technical writing.
theme: just-the-docs
color_scheme: my_scheme

url: https://just-the-docs.github.io